name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  all:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [Windows, Ubuntu, MacOS]

    steps:
    - uses: actions/checkout@v1
    - uses: excitedleigh/setup-nox@0.1.0
    - run: nox
